### PR TITLE
Made some shiny textures.

### PR DESCRIPTION
**Pull request by Tim79000**
Yay!

### CODE REVIEW

**Comment by grorp** [comment]
Hi, thank you very much for your contribution! I really like these textures. I assume you share them under the same license as the textures that are already in the repository, CC BY-SA 4.0? 

I'd like to propose a few small changes, please have a look at them and tell me if you are okay with them. (I'm going to commit & push them soon.)

**Comment by Tim79000** [comment]
Yeah, they use the same license.

**Comment by Tim79000** [comment]
Also, the textures are final for me, but if you have problems with them, you can always ask.

**Comment by grorp** [comment]
> Also, the textures are final for me, but if you have problems with them, you can always ask.

Oh, okay. Since you enabled the"Allow maintainers to edit" or something checkbox, I thought it was okay to just push my desired changes to your branch. What I did is the following:
 - I increased the "darkening effect" of `ggraffiti_spray_can_color.png` to make the effect more visible.
 - I swapped the leftmost and the rightmost pixel of the 4 pixels wide line at the top of the spray can to make the shading more consistent.
 - I changed the red cross back into a red diagonal line. To me, the cross somehow doesn't really look like a cross, but just like a cluster of pixels.

Most of this is probably just personal preference and I'm (as you can see by looking at my original textures) no artist. Are you okay with my changes or would you like to change something again and/or undo my changes?

**Comment by Tim79000** [comment]
I am ok with your changes.

**Comment by grorp** [comment]
Merged it!
7e37996d18a27ac3079618f64ca000c2d0d3dd66 & 4fca7cf9c9205ba69b11319b653de67b56405995
I didn't use the merge button on GitHub, so the PR is shown as closed rather than as merged.
Thank you very much again. I'll also credit you in the README.

**Pull request closed without merging**
